# Generated by Django 3.2.7 on 2021-10-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20211019_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
    ]
