# Generated by Django 3.2.7 on 2021-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_auto_20211019_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
